# Generated by Django 3.1.3 on 2020-11-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('contact', models.CharField(max_length=20, verbose_name='연락처')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=5, verbose_name='성별')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('role', models.CharField(choices=[('제출자', '제출자'), ('평가자', '평가자'), ('관리자', '관리자')], max_length=10, verbose_name='역할')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MappingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derived_schema_name', models.CharField(max_length=45, verbose_name='파생 스키마 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='태스크 이름')),
                ('minimal_upload_frequency', models.CharField(max_length=45, verbose_name='최소 업로드 주기')),
                ('activation_state', models.BooleanField(default=False, verbose_name='활성화 상태')),
                ('description', models.CharField(max_length=100, verbose_name='태스크 설명')),
                ('original_data_description', models.CharField(max_length=100, verbose_name='원본 데이터 설명')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=45, verbose_name='컬럼 레이블')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_definition', to='collect.task', verbose_name='태스크')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_number', models.IntegerField(verbose_name='제출 회차')),
                ('start_date', models.DateField(verbose_name='수집 시작 날짜')),
                ('end_date', models.DateField(verbose_name='수집 종료 날짜')),
                ('total_tuple', models.IntegerField(verbose_name='전체 튜플 수')),
                ('duplicated_tuple', models.IntegerField(verbose_name='중복 튜플 수')),
                ('null_ratio', models.FloatField(verbose_name='null 비율')),
                ('grading_score', models.IntegerField(blank=True, null=True, verbose_name='평가 점수')),
                ('pass_state', models.BooleanField(blank=True, default=None, null=True, verbose_name='패스 여부')),
                ('grading_end_date', models.DateField(verbose_name='평가 종료 날짜')),
                ('file_original', models.FileField(blank=True, null=True, upload_to='data_original/', verbose_name='파일')),
                ('file_parsed', models.FileField(blank=True, null=True, upload_to='data_parsed/', verbose_name='처리된 파일')),
                ('derived_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_parsing_schema', to='collect.mappinginfo', verbose_name='파생 스키마')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_grades', to='collect.account', verbose_name='평가자')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_submits', to='collect.account', verbose_name='제출자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsedfiles', to='collect.task', verbose_name='태스크')),
            ],
        ),
        migrations.CreateModel(
            name='MappingPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_column_name', models.CharField(max_length=45, verbose_name='파생 스키마 속성 레이블')),
                ('mapping_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_info_attribute', to='collect.mappinginfo', verbose_name='매핑 정보')),
                ('schema_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_schema_to_unique_schema_mapping', to='collect.schemaattribute', verbose_name='고유 스키마 속성')),
            ],
        ),
        migrations.AddField(
            model_name='mappinginfo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_info', to='collect.task', verbose_name='파생 스키마 매핑 정보'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.BooleanField(default=False, verbose_name='승인 상태')),
                ('submit_count', models.IntegerField(default=0, verbose_name='제출 횟수')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='collect.account', verbose_name='제출자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='collect.task', verbose_name='태스크')),
            ],
            options={
                'unique_together': {('account', 'task')},
            },
        ),
    ]
